stages:
  - playwright-test

test:
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  stage: playwright-test
  script:
    - npm install
    - npm run test
    - ls -R
  when: manual
  artifacts:
    when: always
    paths:
      - playwright-report
    expire_in: 1 day