name: Playwright Test

on:
  push:
    branches:
      - main          # Trigger on push to the 'main' branch
      - firstcommit   # Trigger on push to the 'firstcommit' branch
  pull_request:
    branches:
      - main          # Trigger on pull request to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Install Playwright browsers
        run: |
          npx playwright install  # This installs the required browsers

      - name: Run Playwright tests
        run: |
          npm run test -- --workers=4

      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
